extends SceneTree

## Generates the Web selected-resource manifest from the actual 3D entry flow.
## ResourceLoader follows scene dependencies; EXPLICIT_RUNTIME_RESOURCES covers
## string-based load() calls that Godot cannot discover statically.

const ROOT_SCENES := [
	"res://levels/main_menu_3d.tscn",
	"res://levels/main_menu.tscn",
	"res://levels/boot.tscn",
	"res://levels/dungeon_3d.tscn",
]

const EXPLICIT_RUNTIME_RESOURCES := [
	"res://common/audio_director.gd",
	"res://ui/dungeon_status_bars_3d.gd",
	"res://materials/exterior/ashen_rock.tres",
	"res://materials/exterior/ashen_dead_bark.tres",
	"res://materials/exterior/ashen_soul_rune.tres",
	"res://materials/interior/soot_stone.tres",
	"res://materials/interior/stone_edge.tres",
	"res://materials/interior/decayed_wood.tres",
	"res://materials/interior/bone_dust.tres",
	"res://materials/interior/tarnished_iron.tres",
	"res://materials/interior/old_blood.tres",
	"res://assets/audio/music/ancient_caverns.ogg",
	"res://assets/audio/music/boss_battle.ogg",
	"res://assets/audio/sfx/ability_learn.mp3",
	"res://assets/audio/sfx/item_pickup.mp3",
	"res://assets/audio/sfx/level_up.mp3",
	"res://assets/audio/sfx/level_up_fanfare.wav",
	"res://assets/audio/sfx/sword_hit_01.ogg",
	"res://assets/audio/sfx/sword_hit_02.ogg",
	"res://assets/audio/sfx/sword_hit_03.ogg",
	"res://assets/audio/sfx/sword_swing_01.ogg",
	"res://assets/audio/sfx/sword_swing_02.ogg",
	"res://assets/audio/sfx/sword_swing_03.ogg",
	"res://assets/audio/sfx/sword_whoosh_01.wav",
	"res://assets/audio/sfx/sword_whoosh_02.wav",
	"res://assets/audio/sfx/sword_whoosh_03.wav",
	"res://assets/audio/sfx/sword_whoosh_04.wav",
	"res://assets/audio/sfx/sword_whoosh_05.wav",
	"res://assets/audio/sfx/sword_whoosh_06.wav",
	"res://assets/audio/sfx/sword_whoosh_07.wav",
	"res://assets/audio/sfx/sword_whoosh_08.wav",
	"res://assets/audio/sfx/sword_whoosh_09.wav",
	"res://assets/audio/sfx/transition.mp3",
	"res://assets/audio/sfx/ui_confirm.mp3",
	"res://assets/ui/ability_icons/single-1.png",
	"res://assets/ui/ability_icons/single-2.png",
	"res://assets/ui/ability_icons/single-3.png",
	"res://assets/ui/ability_icons/single-4.png",
	"res://assets/ui/main_menu/ashen_covenant-title-bg-cute-v1.png",
	"res://assets/ui/loading/ashen_covenant-loading-bg-cute-v1.png",
	"res://assets/ui/prologue/ashen_covenant-prologue-front-alert-v2.png",
	"res://assets/ui/prologue/ashen_covenant-prologue-front-worried-v2.png",
	"res://assets/ui/prologue/ashen_covenant-prologue-front-determined-v2.png",
	"res://assets/fonts/NotoSansTC-runtime.ttf",
]

const OUTPUT_PATH := "res://web_export_files.txt"


func _init() -> void:
	var pending: Array[String] = []
	pending.append_array(ROOT_SCENES)
	pending.append_array(EXPLICIT_RUNTIME_RESOURCES)
	var visited := {}
	var missing: Array[String] = []

	while not pending.is_empty():
		var candidate: String = String(pending.pop_back())
		var path: String = _resource_path(candidate)
		if not path.begins_with("res://") or visited.has(path):
			continue
		visited[path] = true
		if not ResourceLoader.exists(path):
			missing.append(path)
			continue
		var dependencies := ResourceLoader.get_dependencies(path)
		for dependency in dependencies:
			var dependency_path := _resource_path(String(dependency))
			if dependency_path.begins_with("res://") and not visited.has(dependency_path):
				pending.append(dependency_path)

	var files: Array[String] = []
	for path in visited.keys():
		files.append(String(path))
	files.sort()
	var output := PackedStringArray()
	for path in files:
		output.append(path)
	var file := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Unable to write %s" % OUTPUT_PATH)
		quit(1)
		return
	file.store_string("# Generated by tools/generate_web_export_manifest.gd\n")
	for path in output:
		file.store_line(path)
	file.close()
	print("WEB_EXPORT_MANIFEST_OK files=%d missing=%d" % [output.size(), missing.size()])
	if not missing.is_empty():
		for path in missing:
			push_warning("Missing runtime resource: %s" % path)
	quit(0)


func _resource_path(value: String) -> String:
	var uid_separator := value.find("::::")
	if uid_separator >= 0:
		return value.substr(uid_separator + 4)
	var local_separator := value.find("::")
	return value.substr(0, local_separator) if local_separator >= 0 else value
